### ISSUE TITLE
Ability的生命周期有哪几个状态？

### ISSUE THREAD

**Issue by waylau** [waylau/harmonyos-exam#12]
Ability的生命周期有哪几个状态？

A. Create

B. WindowStageCreate

C. Foreground

D. Background

E. WindowStageDestroy

答：正确的是ACD，但题库里面的答案是错的可能是ACDE

**Comment by zeng0813** [comment]
这题答案应该也不正确。
我遇到的题目是下面这个，答案是ACDF
UIAbility的生命周期有哪几个状态？
A. Create
B. WindowStageCreate
C. Foreground
D. Background
E. WindowStageDestroy
F. Destroy

**Comment by waylau** [comment]
@zeng0813  嗯，UIAbility的生命周期包括Create、Foreground、Background、Destroy四个状态

**Comment by waylau** [comment]
@zeng0813  嗯，UIAbility的生命周期包括Create、Foreground、Background、Destroy四个状态
