### ISSUE TITLE
下列哪些组件可以包含子组件？

### ISSUE THREAD

**Issue by waylau** [waylau/harmonyos-exam#96]
下列哪些组件可以包含子组件？

* A. Row
* B. Column
* C. Button
* D. Text

答：系统里面的答案是ABC。但这个题目正确答案是 ABCD。
Text可以包含[Span](https://developer.harmonyos.com/cn/docs/documentation/doc-references-V3/ts-basic-components-span-0000001478181409-V3)子组件。

**Comment by zeng0813** [comment]
答案错了

**Comment by zeng0813** [comment]
ABCD

**Comment by waylau** [comment]
@zeng0813 是的，感谢反馈。
